# Generated by Django 4.2.1 on 2023-05-31 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0005_auto_20220302_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='deadline',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tache_effectue', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.employees')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.projet')),
                ('tache_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.tache')),
            ],
        ),
    ]
