# Generated by Django 4.2.1 on 2023-06-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0006_tache_deadline_performance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='tache_effectue',
        ),
    ]
