# Generated by Django 4.2.1 on 2023-06-01 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0008_alter_tache_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='tache_field',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='employee_information.tache'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En Cours'), ('complet', 'Complet')], max_length=20),
        ),
    ]
