# Generated by Django 4.2.1 on 2023-06-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0009_performance_tache_field_alter_tache_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='projet_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_information.projet'),
        ),
    ]
