# Generated by Django 4.2.1 on 2023-06-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0010_tache_projet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tache',
            old_name='projet_id',
            new_name='projet',
        ),
    ]
