# Generated by Django 4.2.1 on 2023-06-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0010_tache_projet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='projet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_information.projet'),
        ),
    ]
