# Generated by Django 4.2.1 on 2023-06-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0011_rename_projet_id_tache_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='projet_id',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='tache_id',
        ),
        migrations.AddField(
            model_name='employees',
            name='projet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_information.projet'),
        ),
        migrations.AddField(
            model_name='employees',
            name='tache',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_information.tache'),
        ),
    ]
