# Generated by Django 4.2.1 on 2023-06-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0012_remove_employees_projet_id_remove_employees_tache_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='tache',
        ),
    ]
