# Generated by Django 4.2.1 on 2023-06-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0011_alter_tache_projet'),
        ('employee_information', '0013_remove_employees_tache'),
    ]

    operations = [
    ]
