# Generated by Django 4.2.1 on 2023-06-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0014_merge_20230604_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='tache_id',
            new_name='tache',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='projet',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='tache_field',
        ),
        migrations.AddField(
            model_name='performance',
            name='tache_effectue',
            field=models.BooleanField(default=False),
        ),
    ]
