# Generated by Django 4.2.1 on 2023-06-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0015_rename_tache_id_performance_tache_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='tache_effectue',
            field=models.IntegerField(default=0),
        ),
    ]
